### ISSUE TITLE
if the header  like this android:layout_height="wrap_content"

### ISSUE THREAD

**Issue by xiaogu-space** [noties/Scrollable#10]
<TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/header_background"
            android:textColor="@color/white"
            android:textSize="30sp"
            android:text="Header"
            android:id="@+id/header"
            android:gravity="center"/>

the textview's height is changged ,how can i use it?

**Comment by noties** [comment]
@gushoubang Well, try wrapping TextView in a ViewGroup with fixed height or set TextView's height to some dimen. `gravity="center"` will center text inside TextView.

**Comment by xiaogu-space** [comment]
Well，I want to use ImageView instead of Textview，but the picture come from the net,I do not know the height.

**Comment by noties** [comment]
I guess, that simplest solution would be setting fixed height for your ImageView & setting `scaleType="centerCrop"`. That way image would stretch to ImageView's bounds.
But if there is a need for **pixel-perfect** image displaying I would recommend obtaining a Bitmap & updating ImageView's layoutParams.height & ScrollableLayout.setMaxScrollDistance()
