### ISSUE TITLE
Not Support Toolbar

### ISSUE THREAD

**Issue by w4lle** [noties/Scrollable#12]
use toolbar will stay two toolbar height ,one is toolbar ,another is white background whitout noting.like this 
![qq20150603-1](https://cloud.githubusercontent.com/assets/7310246/7953237/fa097e48-09f4-11e5-8525-0cd0a279b14e.png)

because the ScrollLayout method onLayout , child onLayout with childTop use the given top.
if use given top = 0 , the issue will be solved. should you fix it ? thx
code ：
    @Override
    protected void onLayout(boolean changed, int left, int top, int right, int bottom) {
        int childTop = top;
       // should use 
        //childTop = 0;
        for (int i = 0; i < getChildCount(); i++) {
            final View view = getChildAt(i);
            view.layout(left, childTop, right, childTop + view.getMeasuredHeight());
            childTop += view.getMeasuredHeight();
        }
    }

**Comment by noties** [comment]
Thanks for contribution!)
Merged in fe1e4aaff8ecb6f7a5e333697464d9a1334e14d3
