### ISSUE TITLE
No such property: GROUP for class

### ISSUE THREAD

**Issue by 1371030** [noties/Scrollable#14]
Error:FAILURE: Build failed with an exception.
- Where:
  Script 'https://raw.githubusercontent.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle' line: 48
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > A problem occurred configuring project ':library'.
  > No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by noties** [comment]
@1371030 why would you deploy library to Maven? :) Just comment out line `apply from: 'https://raw.githubusercontent.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'` from build.gradle if you want to build library from source.

**Comment by AndroidDeveloperLB** [comment]
This should be fixed in the code itself. It's quite annoying that about half the repos out there require you to change something in the code to even compile... :(
Please, at least put these instructions on the main page of the repo.
