### ISSUE TITLE
can't use viewpager in the header part instead of textview?

### ISSUE THREAD

**Issue by jboeyin** [noties/Scrollable#17]
Hi, it is a awesome project, I just met a problem, I wanna replace the textview control of the header with a viewpager, but it seems being failed, and the listview move to the header, how to fix it?

**Comment by noties** [comment]
Hi, I used ViewPager as a header in one of my projects, and it worked just fine. Maybe you could provide me with more details?

**Comment by jboeyin** [comment]
I using the LinearLayout replace the textview in the header, then I add a viewpager into the LinearLayout, and the whole layout is within a fragment, however it is not working. can you show me your codes?

<ru.noties.scrollable.ScrollableLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/scrollable_layout"
    app:scrollable_maxScroll="@dimen/header_height"
    app:scrollable_considerIdleMillis="125"
    app:scrollable_friction="0.075"
    app:scrollable_closeUpAnimationMillis="250"
    app:scrollable_defaultCloseUp="true"
    app:scrollable_scrollerFlywheel="false"
    app:scrollable_closeUpAnimatorInterpolator="@android:anim/accelerate_decelerate_interpolator">

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/header_height"
        android:background="@color/header_background"
        android:id="@+id/header"
        android:gravity="center">

       <android.support.v4.view.ViewPager
            android:layout_width="match_parent"
           android:layout_height="match_parent"
           android:id="@+id/banner_pager" />

    </LinearLayout>

    <ru.noties.scrollable.sample.TabsLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/tabs_height"
        android:background="@color/tabs_background"
        android:id="@+id/tabs" />

</LinearLayout>

<android.support.v4.view.ViewPager
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginTop="@dimen/tabs_height"
    android:id="@+id/view_pager" />
```

</ru.noties.scrollable.ScrollableLayout>

**Comment by noties** [comment]
The code looks just fine (although I would eliminate ViewPager's LinearLayout in header). Maybe you could be more specific about `the listview move to the header` I don't quite get it.

**Comment by noties** [comment]
I've added a ScrollableFragment to the sample application to show how ScrollableLayout could be used inside a Fragment with a ViewPager as a header
