### ISSUE TITLE
Can this ScrollableLayout be used in fragment's layout? 

### ISSUE THREAD

**Issue by shaopx** [noties/Scrollable#18]
when i use this in fragment layout, it is just not working.  dont know why.

**Comment by noties** [comment]
Hi! I've added a ScrollableFragment to the sample application to show how ScrollableLayout could be used inside a Fragment. Hope this helps

**Comment by jjhesk** [comment]
+1 child nested fragment also.

**Comment by noties** [comment]
I guess that we are done here...
