### ISSUE TITLE
Problem scrolling Up

### ISSUE THREAD

**Issue by FunnyDevs** [noties/Scrollable#20]
Hi!
I have a viewpager with only one fragment and inside this fragment a recyclerview. When i scroll down there is no problem, but when i want to scroll up until the top, the recyclerview is blocked and instead the ScrollableLayout scroll. I wish that the ScrollableLayout would scroll only after the recyclerview reached the top.

**Comment by noties** [comment]
Wow! That was fast! I assume that the problem was similar to #19...
