### ISSUE TITLE
After scrolling to viewpager list bottom, flinging up doesn't show the header

### ISSUE THREAD

**Issue by ayz4sci** [noties/Scrollable#21]
Hi,

After scrolling down to the bottom of a list of about 50 items, when you fling up it doesn't show the header, one will still slide up to finally see the header. I've set the friction to 1f but this scenario still persists. 

Is there anyway to resolve this?

**Comment by noties** [comment]
Well, if a fling gesture had enough velocity, header will be show. Else one has to do the 'final' vertical swipe. I'm afraid fully 'native' scrolling could not be achieved right now. Although it's the case only for fling gestures, swipes are doing alright.

**Comment by tonespy** [comment]
Lol @ayz4sci
