### ISSUE TITLE
bugs with a very large header height

### ISSUE THREAD

**Issue by sidey** [noties/Scrollable#22]
Hi Dimitry,
if the header's height was longer than the screen height, it works not well

**Comment by sidey** [comment]
I fixed it,only if the container of header (such as LinearLayout in your example) has an EXACTLY HEIGHT.
if the header container's height was "WRAP_CONTENT" , the measuredHeight of this container is smaller than the sum of children's measuredHeight, which cause onLayout in ScrollableLayout works not well.

**Comment by noties** [comment]
Hi!
Well, yes, it works well when the size is fixed. I intentionally did so keeping in mind the performance. I guess I could add the possibility to specify wrap_content for the header in future versions

**Comment by Xinng** [comment]
@w4lle @noties I solve it by [this link](http://stackoverflow.com/a/15578844). I add a global layout listener for the header view `addOnGlobalLayoutListener`. In the callback method `onGlobalLayout` set the max scrollable distance for the scrollable layout : `scrollable_layout.setMaxScrollY(mHeader.getHeight());`

**Comment by noties** [comment]
There is an `autoMaxScroll` option now (for a long time actually), that automatically calculates `maxScroll` and keeps it updated (listens via GlobalLayoutListener)
