### ISSUE TITLE
Scroll in header area.

### ISSUE THREAD

**Issue by sidey** [noties/Scrollable#23]
Hi Dimitry,
sorry to disturb you again.
in my layout,i got a complex header view longer than the screen height,which has ImageView,ViewPager etc.all of the cell views in header are clickable.
it seems a little lag during scroll,unless the TabsLayout is sticky.
you can add a couple of TextViews in a vertical linearlayout  header,and every TextView has a click listener.

**Comment by noties** [comment]
Hi!
I don't think that lags are connected with OnClickListeners. Could you please post to me a gif or something that I could visualize the problem?
