### ISSUE TITLE
 Proguard,can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath

### ISSUE THREAD

**Issue by captain-miao** [noties/Scrollable#25]
Warning:ru.noties.scrollable.ScrollableScroller: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath
Warning:there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Exception while processing task 
java.io.IOException: Please correct the above warnings first.Error:Execution failed for task 
...
...

':app:packageRelease'.

> Unable to compute hash of /Users/captain_miao/am/androidCode/trunk/treadmill/app/build/intermediates/classes-proguard/release/classes.jar

**Comment by noties** [comment]
Well, it's a shame really. I will remove FloatMath from Scroller

**Comment by captain-miao** [comment]
wonderful
