### ISSUE TITLE
Disable Scroll on Header section touch

### ISSUE THREAD

**Issue by manishpatidar** [noties/Scrollable#28]
I want to disable scroll when touched on header area because there is a list in and a view pager
![screenshot_8](https://cloud.githubusercontent.com/assets/4478996/12115716/835472f4-b3da-11e5-8339-a3ec9da4b5ae.png)

**Comment by noties** [comment]
Hi! Sorry, that it took me so long. You can call `setSelfUpdateScroll(boolean)` and Scrollable won't process touch events if passed `true`.
