### ISSUE TITLE
Closeup Logic

### ISSUE THREAD

**Issue by squeeish** [noties/Scrollable#29]
Hi,

Is it possible to implement CloseUpAlgorithm such that the header doesn't expand and hide automatically? What I mean is, when the header is fully expanded, if I move my finger upwards till the header is half of its original height and release my finger, the header doesn't collapse but remains as it is.

I'm very new to development with regards to touch events so I'd be grateful if you could point me in the right direction.

Thanks!

**Comment by noties** [comment]
Hi! If you don't specify CloseUpAlgorithm, the scroll state won't changed after touch event is finished. It can be done with xml: `app:scrollable_defaultCloseUp="false"` (which is default) or via code `ScrollableLayout.setCloseUpAlgorithm(null)`

**Comment by squeeish** [comment]
Ah I didn't read properly then. Thanks! That cleared that up.
