### ISSUE TITLE
Compatibility with SwipeRefreshLayout

### ISSUE THREAD

**Issue by squeeish** [noties/Scrollable#30]
Does this work with the support library's SwipeRefreshLayout? :)

**Comment by noties** [comment]
I don't see a reason why it won't :). I tested `SwipeRefreshLayout` included in the view under header & it worked. I didn't test wrapping `ScrollableLayout` inside `SwipeRefreshLayout` though...

**Comment by squeeish** [comment]
I'm in the midst of implementing it. WIll update this thread if it works for `ScrollableLayout` inside a `SwipeRefreshLayout`.
