### ISSUE TITLE
Disable all logs

### ISSUE THREAD

**Issue by GauravP123** [noties/Scrollable#31]
how to disable all logs 
D/InputEventConsistencyVerifier: TouchEvent: ACTION_MOVE contained 1 pointers but there are currently 0 pointers down.
                                                                                in ru.noties.scrollable.ScrollableLayout@b552f9f0
                                                                                0: sent at 8776594648936, MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=128.0, y[0]=97.18901, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=8776594, downTime=8776490, deviceId=0, source=0x1002 }
                                                                                -- recent events --
                                                                                1: sent at 8776594648936, (unhandled) MotionEvent { action=ACTION_CANCEL, id[0]=0, x[0]=128.0, y[0]=97.18901, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=8776594, downTime=8776490, deviceId=0, source=0x1002 }
                                                                                2: sent at 8776577982270, MotionEvent { action=ACTION_CANCEL, id[0]=0, x[0]=128.0, y[0]=90.14987, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=8776577, downTime=8776490, deviceId=0, source=0x1002 }
                                                                                3: sent at 8776561315604, MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=128.0, y[0]=84.162964, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=8776561, downTime=8776490, deviceId=0, source=0x1002 }
                                                                                4: sent at 8776490710000, MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=128.0, y[0]=82.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=8776490, downTime=8776490, deviceId=0, source=0x1002 }
                                                                                5: sent at 8776490065000, MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=127.0, y[0]=79.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=8776490, downTime=8776490, deviceId=0, source=0x1002 }

**Comment by noties** [comment]
Hi! I haven't seen these messages on my devices.. But I assure you, it's not the library who logges them (system does :)).

**Comment by GauravP123** [comment]
can we hide tool bar when one view is sticky while scrolling down  ?
