### ISSUE TITLE
NoClassDefError for ScrollableLayout

### ISSUE THREAD

**Issue by suyashbhagwat** [noties/Scrollable#32]
Used design support library in my project , while using scrollable layout getting error as

**Error:** 
java.lang.**NoClassDefFoundError**:  ru.noties.scrollable.ScrollableLayout$2
 at  ru.noties.scrollable.ScrollableLayout.<init>(ScrollableLayout.java:521) 

Is there any solution for it?
I have used design support library with version 23.1.1

Thanks

**Comment by noties** [comment]
Hi! I don't think that it's related with design support library. Do you use `proguard`?
