### ISSUE TITLE
bugs in multi-window mode

### ISSUE THREAD

**Issue by nuister** [noties/Scrollable#38]
In multi-window mode, screen height maybe shorter than scroll header height.

**Comment by noties** [comment]
Hi!
Yes, there is a problem when header height is greater than total height of ScrollableLayout. But. You should modify manifest to indicate what minimum height of a screen do you support. Also, header can be dynamic and ScrollableLayout can listen to the changes that occur to it's height and apply `maxScroll` accordingly (`autoMaxScroll` property).
