### ISSUE TITLE
Direction variable not available in setCanScrollVerticallyDelegate

### ISSUE THREAD

**Issue by Supratimwy** [noties/Scrollable#4]
I am using your library to implement a sliding up panel layout which has a scrollable layout at its root and a view pager as a child which will show two fragments 

the setCanScrollVerticallyDelegate method on debugging gave me the result that the direction variable doesnt have a value 

Can you help me out please

**Comment by noties** [comment]
Hi!
I'm not really sure what's wrong, but maybe you forgot to implement CanScrollVerticallyDelegate in your Fragments?

**Comment by Supratimwy** [comment]
Actually i found out , the direction is not the issue , actually the scrollview in my layout of the fragment (which gets added in the viewpager ) is giving mscrollview.canscrollVertically(direction) as false ?

Its a regular scrollview in the layout of my fragment
