### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by Cheesebaron** [noties/Scrollable#5]
strings.xml is missing `min_friction_text`
dimension.xml is missing `max_friction_steps`

So right now it isn't compiling until you add those :)

**Comment by noties** [comment]
Hi!
These values are added dynamically during gradle build (they are initialized in build.gradle script). So, you have to `sync with gradle` the sample project in order for them to be generated.

**Comment by Cheesebaron** [comment]
Ahh ok. Thanks I am in the middle of porting to Xamarin.Android, didn't really think about looking for those in gradle :)

Will post when the port is up :)

**Comment by noties** [comment]
Wow! Keep us up-to-date)

**Comment by Cheesebaron** [comment]
@noties hey, I've made the port, but there is something wrong with it.

Flinging the view seems to work, it locks to the Tabs in the top of the view. However, if I then try to scroll the `ScrollView`, `ListView` or whatever is under. Nothing happens.

Also if I scroll slowly it pushes the tabs up and a white area occurs after the `ScrollView` or whatever view is under the Tabs. Maybe you have some pointers on what would be going wrong here?

**Comment by hoangwy** [comment]
Hi Cheesebaron,
Are you done for xamarin on this lib?
Thank you!

**Comment by Cheesebaron** [comment]
@hoangwy I think it is on one of my computers somewhere. Didn't finish it all up. If you are interested in the code, I can look at digging it up.
