### ISSUE TITLE
dependencies problem

### ISSUE THREAD

**Issue by lozn00** [noties/Scrollable#53]
dependencies does not prompt for errors, it is also synchronized, but you can't find the class dependencies {
    compile 'ru.noties:scrollable:1.3.0' }  Restart, still not in effect

**Comment by noties** [comment]
Make sure that you have `jcenter` and/or `mavenCentral` in your repositories block in `build.gradle`. For example:
```gradle
repositories {
    jcenter()
    mavenCentral()
}

apply plugin: 'com.android.application'
// other content omitted
```
