### ISSUE TITLE
Scrolling is slow and lagy

### ISSUE THREAD

**Issue by DavidPacioianu** [noties/Scrollable#6]
I am using a recyclerView and if I scroll and after let it free to scroll itself, the move is very slow with a lot of friction.
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/10657845/7119165/9dd37ddc-e20c-11e4-9db8-e18a382a7155.gif)

**Comment by noties** [comment]
Hi!
Yes, I'm sorry I didn't make it clear. There is a parameter called friction. By default ScrollableLayout uses default system friction from ViewConfiguration. You may experiment with it in the sample application (where is a seekbar in configuration tab). And finally set it with `scrollableLayout.setFriction(float)`

**Comment by DavidPacioianu** [comment]
@noties I have tried this before but I cant find the min friction value, if I setFriction to 0.0f , scrolling is even slower. Which is the best vale to use for no friction scroll?

**Comment by noties** [comment]
Well, to my own taste something between 0.045F and 0.07F looks ok

**Comment by noties** [comment]
Well, 1.F will give you look & feel of `no friction` scroll, but try something between 0.045F and 0.07F, to my own taste it looks ok.

**Comment by DavidPacioianu** [comment]
@noties I found that the problem is not the friction, my problem is that I have to scroll once just for getting ride of the header. I would like it to work like a real list header, to have a continuous scroll all the way from the header to the bottom.

**Comment by noties** [comment]
Can you share your code with me (xml & java)? Maybe pm or something...

**Comment by e-Joe** [comment]
I have a sam problem  just when using grid layout with 3 columns.

**Comment by e-Joe** [comment]
Actually I have this problem  just  with he first fragments in view pager. Please help me ?

**Comment by noties** [comment]
Hi!
I found out that some device has own very specific Scroller implementation, so I bundled Scrollable with Scroller from AOSP (api 22) in 1.1.2. Please give me a feedback if that helped.
