### ISSUE TITLE
bottom part of the fragment in the viewpager is clipped or cut of how to fix this

### ISSUE THREAD

**Issue by xbahaa** [noties/Scrollable#63]
hello 

i have a view pager with fragment in the scrollable , when i scroll down you can notics that the bottom part of the fragment in the viewpager is clipped or cut of how to fix this

**Comment by noties** [comment]
Hello @xbahaa !

Well, let's see it. Can you please attach your layout xml and a screenshot of this behaviour?

**Comment by xbahaa** [comment]
https://youtu.be/tgz2fMPRBcc

in the bottom of the view some part of the item is cut of this a tabs and view pager in the viewpager 
there fragment contains a recycle view how to fix this 


<?xml version="1.0" encoding="utf-8"?>
<layout>

    <data>
        <variable
            name="productDetails"
            type=".model.ProductDetails"/>
    </data>

    <android.support.design.widget.CoordinatorLayout
        android:background="@android:color/white"
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        tools:context=".product.details.ProductDetailsActivity"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <include layout="@layout/toolbar_back"/>

   

        <ru.noties.scrollable.ScrollableLayout
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:id="@+id/productDetailsScrollableLayout"
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:scrollable_autoMaxScroll="true"
            app:scrollable_defaultCloseUp="true">

            <RelativeLayout
                android:id="@+id/headerProductDetails"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <android.support.constraint.ConstraintLayout
                    android:layout_centerInParent="true"
                    android:background="@drawable/rectangle_shape_silver"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="5dp"
                    android:layout_marginStart="10dp"
                    android:layout_marginEnd="10dp"
                    android:layout_marginBottom="5dp">

                    <android.support.v7.widget.AppCompatImageView
                        android:id="@+id/imageProductDetailsItem"
                        android:layout_width="70dp"
                        android:layout_height="70dp"
                        android:layout_marginStart="12dp"
                        android:layout_marginTop="12dp"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:srcCompat="@drawable/ic_icon_gray" />

                    <android.support.v7.widget.AppCompatTextView
                        android:id="@+id/productNameProductDetailsItem"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="32dp"
                        android:layout_marginEnd="8dp"
                        android:layout_marginStart="16dp"
                        android:text="@{productDetails.name}"
                        android:textColor="@color/scorpion"
                        android:textSize="14sp"
                        app:layout_constraintBottom_toBottomOf="@+id/imageProductDetailsItem"
                        app:layout_constraintEnd_toStartOf="@+id/productPriceOfferProductDetailsItem"
                        app:layout_constraintStart_toEndOf="@+id/imageProductDetailsItem"
                        app:layout_constraintTop_toTopOf="@+id/imageProductDetailsItem" />

                    <android.support.v7.widget.AppCompatTextView
                        android:id="@+id/vendorNameProductDetailsItem"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="8dp"
                        android:textColor="@color/scorpion"
                        android:textSize="13sp"
                        app:layout_constraintEnd_toStartOf="@+id/productPriceProductDetailsItem"
                        app:layout_constraintStart_toStartOf="@+id/productNameProductDetailsItem"
                        app:layout_constraintTop_toBottomOf="@+id/productNameProductDetailsItem" />

                    <com.iarcuschin.simpleratingbar.SimpleRatingBar
                        android:id="@+id/ratingViewProductDetailsItem"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="4dp"
                        app:layout_constraintStart_toStartOf="@+id/vendorNameProductDetailsItem"
                        app:layout_constraintTop_toBottomOf="@+id/vendorNameProductDetailsItem"
                        app:srb_borderColor="@color/silver1"
                        app:srb_fillColor="@color/colorPrimary"
                        app:srb_numberOfStars="5"
                        app:srb_starBorderWidth="2"
                        app:srb_starSize="15dp"
                        app:srb_stepSize="0.5" />

                    <View
                        android:id="@+id/clickRatingViewProductDetailsItem"
                        android:layout_width="0dp"
                        android:layout_height="0dp"
                        app:layout_constraintBottom_toBottomOf="@+id/ratingViewProductDetailsItem"
                        app:layout_constraintEnd_toEndOf="@+id/ratingViewProductDetailsItem"
                        app:layout_constraintStart_toStartOf="@+id/ratingViewProductDetailsItem"
                        app:layout_constraintTop_toTopOf="@+id/ratingViewProductDetailsItem" />

                    <android.support.v7.widget.AppCompatTextView
                        android:id="@+id/productPriceOfferProductDetailsItem"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="16dp"
                        android:textColor="@android:color/holo_red_dark"
                        android:textSize="12sp"
                        app:layout_constraintBottom_toBottomOf="@+id/productNameProductDetailsItem"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintTop_toTopOf="@+id/productNameProductDetailsItem" />

                    <android.support.v7.widget.AppCompatTextView
                        android:id="@+id/productPriceProductDetailsItem"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginEnd="16dp"
                        android:textColor="@color/scorpion"
                        android:textSize="12sp"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/productNameProductDetailsItem" />


                    <android.support.constraint.ConstraintLayout
                        android:id="@+id/constraintLayout"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="16dp"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toBottomOf="@+id/imageProductDetailsItem">

                        <android.support.v7.widget.AppCompatImageButton
                            android:id="@+id/cartProductDetailsItem"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:background="@drawable/rectangle_primary_back_silver_border"
                            android:paddingBottom="5dp"
                            android:paddingTop="5dp"
                            app:layout_constraintBottom_toBottomOf="parent"
                            app:layout_constraintEnd_toStartOf="@+id/wishDetailsProductDetailsItem"
                            app:layout_constraintStart_toStartOf="parent"
                            app:srcCompat="@drawable/ic_cart_small" />

                        <android.support.v7.widget.AppCompatImageButton
                            android:id="@+id/wishDetailsProductDetailsItem"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:background="@drawable/rectangle_primary_back_silver_border"
                            android:paddingBottom="5dp"
                            android:paddingTop="5dp"
                            app:layout_constraintEnd_toStartOf="@+id/shareProductDetailsItem"
                            app:layout_constraintStart_toEndOf="@+id/cartProductDetailsItem"
                            app:layout_constraintTop_toTopOf="@+id/cartProductDetailsItem"
                            app:srcCompat="@drawable/ic_wishlist_small" />

                        <android.support.v7.widget.AppCompatImageButton
                            android:id="@+id/shareProductDetailsItem"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:background="@drawable/rectangle_primary_back_silver_border"
                            android:paddingBottom="5dp"
                            android:paddingTop="5dp"
                            app:layout_constraintEnd_toEndOf="parent"
                            app:layout_constraintStart_toEndOf="@+id/wishDetailsProductDetailsItem"
                            app:layout_constraintTop_toTopOf="@+id/wishDetailsProductDetailsItem"
                            app:srcCompat="@drawable/ic_share_small" />

                    </android.support.constraint.ConstraintLayout>

                </android.support.constraint.ConstraintLayout>

            </RelativeLayout>


            <android.support.design.widget.AppBarLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <android.support.design.widget.TabLayout
                    android:id="@+id/productDetailsTabsLayout"
                    android:layout_width="match_parent"
                    android:layout_height="48dp"
                    android:layout_gravity="bottom"
                    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
                    app:tabBackground="@color/white"
                    app:tabIndicatorColor="@color/primary"
                    app:tabSelectedTextColor="@color/scorpion"
                    app:tabTextColor="@color/gray92"/>

            </android.support.design.widget.AppBarLayout>

            <android.support.v4.view.ViewPager
                android:id="@+id/productDetailsViewPager"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginTop="5dp"/>

        </ru.noties.scrollable.ScrollableLayout>

    </android.support.design.widget.CoordinatorLayout>

</layout>

**Comment by noties** [comment]
Hey @xbahaa !

I didn't notice any cutout on the video... can you share the XML that is used to build the layout?

**Comment by noties** [comment]
@xbahaa try changing the ViewPager like this:

```xml
<android.support.v4.view.ViewPager
    android:id="@+id/productDetailsViewPager"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginTop="48dp"/>
```

It changes the `layout_marginTop` attribute to match the height of the `AppBarLayout`

**Comment by xbahaa** [comment]
thanks for you it;s work's like a charm, but way it's works that's the question?

**Comment by noties** [comment]
@xbahaa it works because:

> ScrollableLayout positions its children like vertical LinearLayout, but measures them like a FrameLayout

This is very important part to know when creating layouts with `ScrollableLayout`. So, if you put 2 views inside a ScrollableLayout with `layout_height="match_parent"` they both will have the same height (equal to the height of ScrollableLayout) but one will be placed under another.
