### ISSUE TITLE
not use SwipeBackLayoutTouTiao

### ISSUE THREAD

**Issue by 1371030** [noties/Scrollable#65]
https://github.com/JustRight815/SwipeBackLayoutTouTiao,return with viewpager horizontal swipe back

**Comment by noties** [comment]
Hello @1371030  !

Sorry, can you be more specific?

**Comment by 1371030** [comment]
Thanks for your response, @noties .

1. The application uses JustRight815/SwipeBackLayoutTouTiao, an open source control
2. Use noties/Scrollable + viewpager in activity
3. Swipe back Conflicts with Viewpager Horizontal Scrolling in Notes/Scrollable

**Comment by noties** [comment]
Have you tried using your swipe-back control with a ViewPager without ScrollableLayout? Because currently I do not see what ScrollableLayout has to do with anything here

**Comment by 1371030** [comment]
I think we can add CanScrollHorizontal Delegate
