### ISSUE TITLE
if the content of Header view is  too much ,The content of headView  to be displaied completely

### ISSUE THREAD

**Issue by ruilyzhu** [noties/Scrollable#7]
how can I solve it?

**Comment by noties** [comment]
Hi!
Can you post a screenshot or something?

**Comment by ruilyzhu** [comment]
here is the screenshot,the headView can't display completely
![screenshot_2015-04-20-00-43-33](https://cloud.githubusercontent.com/assets/7918747/7220364/0d1d8b80-e6f7-11e4-90cb-9e6aeb1922af.png)

**Comment by noties** [comment]
Hi!
Sorry for late reply. Thank for the screenshot, but, I wonder, what element is a header? :)

**Comment by xu6148152** [comment]
I think you used it uncorrectly.

**Comment by noties** [comment]
Did I? :)

**Comment by xu6148152** [comment]
@noties  not you, but @VincentRuiLi

**Comment by noties** [comment]
@xu6148152 :+1:
